version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 10
    groups:
      expo:
        patterns:
          - 'expo*'
          - '@expo/*'
        update-types:
          - 'minor'
          - 'patch'
      react-native:
        patterns:
          - 'react-native*'
          - '@react-native*'
        update-types:
          - 'minor'
          - 'patch'
      tamagui:
        patterns:
          - 'tamagui'
          - '@tamagui/*'
        update-types:
          - 'minor'
          - 'patch'
      testing:
        patterns:
          - 'jest*'
          - '@testing-library/*'
          - 'ts-jest'
        update-types:
          - 'minor'
          - 'patch'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
